// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-my-chart.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-chart.ts
var get_my_chart_default = defineTool({
  name: "get_my_chart",
  title: "Get my Human Design chart",
  description: "Return the signed-in user's Human Design profile: energy type, strategy, authority, profile, definition, incarnation cross, defined centers and gates, PHS variables, and nodal environments.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "display_name, energy_type, strategy, authority, profile, definition, signature, not_self_theme, incarnation_cross, defined_centers, defined_gates, variables, south_node_gate, north_node_gate, south_node_environment, north_node_environment, birth_location, onboarding_completed"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No chart yet \u2014 complete onboarding in the app first." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { chart: data }
    };
  }
});

// src/lib/mcp/tools/list-matches.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_matches_default = defineTool2({
  name: "list_matches",
  title: "List my matches",
  description: "List the signed-in user's matches with chemistry score, dominant connection theme, status, and the partner's Human Design basics.",
  inputSchema: {
    status: z.string().trim().min(1).optional().describe("Optional status filter, e.g. 'active'."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum matches to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("matches").select("id, chemistry_score, dominant_theme, status, user_a, user_b, created_at").or(`user_a.eq.${userId},user_b.eq.${userId}`).order("chemistry_score", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data: matches, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const partnerIds = (matches ?? []).map((m) => m.user_a === userId ? m.user_b : m.user_a);
    const partners = /* @__PURE__ */ new Map();
    if (partnerIds.length) {
      const { data: profiles } = await supabase.from("profiles").select("user_id, display_name, energy_type, authority, profile").in("user_id", partnerIds);
      for (const p of profiles ?? []) partners.set(p.user_id, p);
    }
    const items = (matches ?? []).map((m) => {
      const partnerId = m.user_a === userId ? m.user_b : m.user_a;
      return {
        match_id: m.id,
        chemistry_score: m.chemistry_score,
        dominant_theme: m.dominant_theme,
        status: m.status,
        created_at: m.created_at,
        partner: partners.get(partnerId) ?? { user_id: partnerId }
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { matches: items }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_messages_default = defineTool3({
  name: "list_messages",
  title: "List messages in a match",
  description: "Read the conversation for one of the signed-in user's matches, oldest message first.",
  inputSchema: {
    match_id: z2.string().uuid().describe("Match id from list_matches."),
    limit: z2.number().int().min(1).max(200).default(50).describe("Maximum messages to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ match_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, sender_id, content, created_at").eq("match_id", match_id).order("created_at", { ascending: true }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = (data ?? []).map((m) => ({
      ...m,
      from_me: m.sender_id === ctx.getUserId()
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { messages: items }
    };
  }
});

// src/lib/mcp/tools/send-message.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var send_message_default = defineTool4({
  name: "send_message",
  title: "Send a message to a match",
  description: "Send a chat message as the signed-in user in one of their matches.",
  inputSchema: {
    match_id: z3.string().uuid().describe("Match id from list_matches."),
    content: z3.string().trim().min(1).max(2e3).describe("Message text to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ match_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").insert({ match_id, sender_id: ctx.getUserId(), content }).select("id, match_id, content, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Message sent (${data.id}).` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/list-unleash-checks.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_unleash_checks_default = defineTool5({
  name: "list_unleash_checks",
  title: "List my Unleash Checks",
  description: "List the signed-in user's authority-based Unleash Checks, including when each becomes available, the response, and any reflection.",
  inputSchema: {
    match_id: z4.string().uuid().optional().describe("Optional match id to filter by."),
    limit: z4.number().int().min(1).max(50).default(20).describe("Maximum checks to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ match_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("unleash_checks").select("id, match_id, authority, available_at, answered_at, response, reflection, unleashed, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (match_id) query = query.eq("match_id", match_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { checks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eigfbhrbrcytaalswrhq";
var mcp_default = defineMcp({
  name: "auramatch-connect",
  title: "AuraMatch Connect",
  version: "0.1.0",
  instructions: "Tools for AuraMatch, a Human Design dating app. Use `get_my_chart` for the signed-in user's Human Design blueprint, `list_matches` for their matches and chemistry themes, `list_messages` / `send_message` for a match conversation, and `list_unleash_checks` for authority-based timing checks. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_chart_default, list_matches_default, list_messages_default, send_message_default, list_unleash_checks_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
